version: '3'

services:
  app:
    build: .
    working_dir: /home/rasak/app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/rasak/app
    tty: true
    stdin_open: true
    command: yarn dev